name = "geometry-duel-signaling"
main = "index.js"
compatibility_date = "2024-01-01"
workers_dev = true

[assets]
directory = "../"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "ROOM_KV"
id = "b4eaefe84a7247bf8db25c7aa9e421e2"
